In [23]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
original_goodread_df = pd.read_csv('corrected_goodread_df.csv', error_bad_lines = False)
original_goodread_df.head()

,bookID,title,author,average_rating,isbn,isbn13,language_code,num_pages,audio_hrs,ratings_count,text_reviews_count,publication_date,publisher,series
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.57,439785960,9.780440e+12,eng,652,0.0,2095690,27591,2006-09-16,Scholastic Inc.,True
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,439358078,9.780439e+12,eng,870,0.0,2153167,29221,2004-09-01,Scholastic Inc.,True
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439554896,9.780440e+12,eng,352,0.0,6333,244,2003-11-01,Scholastic,True
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.56,043965548X,9.780440e+12,eng,435,0.0,2339585,36325,2004-05-01,Scholastic Inc.,True
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling,4.78,439682584,9.780440e+12,eng,2690,0.0,41428,164,2004-09-13,Scholastic,True

In [25]:
goodread_df = original_goodread_df.copy()

In [26]:
goodread_df.dtypes

bookID                  int64
title                  object
author                 object
average_rating        float64
isbn                   object
isbn13                float64
language_code          object
num_pages               int64
audio_hrs             float64
ratings_count           int64
text_reviews_count      int64
publication_date       object
publisher              object
series                   bool
dtype: object

In [27]:
#create copy of df to fix datatypes
goodread_copy_df = goodread_df.copy()
goodread_copy_df.head()

goodread_copy_df.dtypes

#update isbn13 to object
goodread_copy_df['isbn13'] = goodread_copy_df['isbn13'].astype(str)

#update publication_date to datetime
goodread_copy_df['publication_date'] = pd.to_datetime(goodread_copy_df['publication_date'])
  
goodread_copy_df.dtypes

bookID                         int64
title                         object
author                        object
average_rating               float64
isbn                          object
isbn13                        object
language_code                 object
num_pages                      int64
audio_hrs                    float64
ratings_count                  int64
text_reviews_count             int64
publication_date      datetime64[ns]
publisher                     object
series                          bool
dtype: object

### Questions to look into:

In [28]:
goodread_copy_df.sort_values(by='ratings_count', ascending=False)

,bookID,title,author,average_rating,isbn,isbn13,language_code,num_pages,audio_hrs,ratings_count,text_reviews_count,publication_date,publisher,series
9653,41865,Twilight (Twilight #1),Stephenie Meyer,3.59,316015849,9780316015844.0,eng,501,0.0,4597666,94265,2006-09-06,Little Brown and Company,True
1591,5907,The Hobbit or There and Back Again,J.R.R. Tolkien,4.27,618260307,9780618260300.0,eng,366,0.0,2530894,32871,2002-08-15,Houghton Mifflin,False
1363,5107,The Catcher in the Rye,J.D. Salinger,3.80,316769177,9780316769174.0,eng,277,0.0,2457092,43499,2001-01-30,Back Bay Books,False
291,960,Angels & Demons (Robert Langdon #1),Dan Brown,3.89,1416524797,9781416524793.0,eng,736,0.0,2418736,21303,2006-04-01,Pocket Books,True
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.56,043965548X,9780439655484.0,eng,435,0.0,2339585,36325,2004-05-01,Scholastic Inc.,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,12225,A Streetcar Named Desire (SparkNotes Literatur...,SparkNotes,3.29,1586634496,9781586634490.0,eng,96,0.0,0,0,2002-07-15,SparkNotes,False
7482,30941,Choo Choo (Carry Along Book & Cassette Favorites),Virginia Lee Burton,3.91,395511682,9780395511688.0,eng,48,0.0,0,0,1989-04-24,Houghton Mifflin,False
3275,12712,Brodie's notes on Aldous Huxley's brave new world,Graham Handley,0.00,333581296,9780333581292.0,eng,71,0.0,0,0,1992-08-20,Macmillan,False
7238,30080,Beckett Football Card Price Guide,Dan Hitt,0.00,1930692471,9781930692473.0,eng,830,0.0,0,0,2006-09-01,Beckett Media,False
10136,44433,Courageous Faith Through the Year,Bill Hybels,3.50,830832947,9780830832941.0,eng,327,0.0,0,0,2004-07-01,IVP Books,False

In [29]:
most_ratings_slice = goodread_copy_df.sort_values(by='ratings_count', ascending=False).head(20)

In [30]:
most_ratings_slice

,bookID,title,author,average_rating,isbn,isbn13,language_code,num_pages,audio_hrs,ratings_count,text_reviews_count,publication_date,publisher,series
9653,41865,Twilight (Twilight #1),Stephenie Meyer,3.59,316015849,9780316015844.0,eng,501,0.0,4597666,94265,2006-09-06,Little Brown and Company,True
1591,5907,The Hobbit or There and Back Again,J.R.R. Tolkien,4.27,618260307,9780618260300.0,eng,366,0.0,2530894,32871,2002-08-15,Houghton Mifflin,False
1363,5107,The Catcher in the Rye,J.D. Salinger,3.80,316769177,9780316769174.0,eng,277,0.0,2457092,43499,2001-01-30,Back Bay Books,False
291,960,Angels & Demons (Robert Langdon #1),Dan Brown,3.89,1416524797,9781416524793.0,eng,736,0.0,2418736,21303,2006-04-01,Pocket Books,True
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.56,043965548X,9780439655484.0,eng,435,0.0,2339585,36325,2004-05-01,Scholastic Inc.,True
4113,15881,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439064864,9780439064866.0,eng,341,0.0,2293963,34692,1999-06-02,Arthur A. Levine Books / Scholastic Inc.,True
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,439358078,9780439358071.0,eng,870,0.0,2153167,29221,2004-09-01,Scholastic Inc.,True
22,34,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,4.36,618346252,9780618346257.0,eng,398,0.0,2128944,13670,2003-09-05,Houghton Mifflin Harcourt,True
1990,7613,Animal Farm,George Orwell,3.93,452284244,9780452284241.0,eng,122,0.0,2111750,29677,2003-05-06,NAL,False
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.57,439785960,9780439785969.0,eng,652,0.0,2095690,27591,2006-09-16,Scholastic Inc.,True
1992,7624,Lord of the Flies,William Golding,3.68,140283331,9780140283334.0,eng,182,0.0,2036679,26199,1999-10-01,Penguin Books,False
4668,18135,Romeo and Juliet,William Shakespeare,3.74,743477111,9780743477116.0,eng,368,0.0,1893917,14637,2004-01-01,Simon Schuster,False
6772,28187,The Lightning Thief (Percy Jackson and the Oly...,Rick Riordan,4.25,786838655,9780786838653.0,eng,375,0.0,1766725,47951,2006-03-01,Disney Hyperion Books,True
279,890,Of Mice and Men,John Steinbeck,3.87,142000671,9780142000670.0,eng,103,0.0,1755253,25554,2002-01-08,Penguin Books,False
292,968,The Da Vinci Code (Robert Langdon #2),Dan Brown,3.84,307277674,9780307277671.0,eng,489,0.0,1679706,35877,2006-03-28,Anchor,True
269,865,The Alchemist,Paulo Coelho,3.86,61122416,9780061122415.0,eng,197,0.0,1631221,55843,1993-05-01,HarperCollins,False
996,3636,The Giver (The Giver #1),Lois Lowry,4.13,385732554,9780385732550.0,eng,208,0.0,1585589,56604,2006-01-24,Ember,True
4916,19063,The Book Thief,Markus Zusak,4.37,375831002,9780375831003.0,eng,552,0.0,1516367,86881,2006-03-14,Alfred A. Knopf,False
550,1934,Little Women,Louisa May Alcott,4.07,451529308,9780451529305.0,eng,449,0.0,1479727,18458,2004-04-06,Signet Classics,False
2602,10210,Jane Eyre,Charlotte Brontë,4.12,142437204,9780142437209.0,eng,532,0.0,1409369,27884,2003-02-04,Penguin,False

In [31]:
least_ratings_slice = goodread_copy_df.sort_values(by='ratings_count').head(20)

#### What gender of the author breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?

#### What is the skin color breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?

In [32]:
most_ratings_slice['author']

9653        Stephenie Meyer
1591         J.R.R. Tolkien
1363          J.D. Salinger
291               Dan Brown
3              J.K. Rowling
4113           J.K. Rowling
1              J.K. Rowling
22           J.R.R. Tolkien
1990          George Orwell
0              J.K. Rowling
1992        William Golding
4668    William Shakespeare
6772           Rick Riordan
279          John Steinbeck
292               Dan Brown
269            Paulo Coelho
996              Lois Lowry
4916           Markus Zusak
550       Louisa May Alcott
2602       Charlotte Brontë
Name: author, dtype: object

In [ ]:
Gender/race/sex breakdown of authors:
    Stephanie Meyer: cis white woman
    JRR Tolkien: cis white man
    JD Salinger: cis white man
    Dan Brown: cis white man
    JK Rowling: cis white woman
    George Orwell: cis white man
    William Golding: cis white man
    William Shakespeare: cis white man
    Rick Riordan: cis white man
    John Steinbeck: cis white man
    Paulo Coelho: cis white-passing Latinx man
    Lois Lowry: cis white woman
    Markus Zusak: cis white man
    Louisa May Alcott: cis white woman
    Charlott Bronte: cis white woman

In [33]:
least_ratings_slice['author']

6477              James M. Kouzes
9488                 Terry Pastor
6343             Andrew      Hunt
6299            Eleanor J. Gibson
6292          Christopher   Black
9584             Sara Barton-Wood
9627              Herman Melville
6063                   Jay Parini
6361              Anthony E. Wolf
5903                Gordon Korman
9750            Glenn M. Schwartz
5599               Elizabeth Berg
9801            James Craig Holte
5343                    Greg Tang
9817         Kenneth H. Blanchard
251                 Lonely Planet
4963                 David   Ward
5890                    John Weld
10123               Babette Smith
9462     Better Homes and Gardens
Name: author, dtype: object

In [34]:
Gender/race/sex breakdown of authors:

9653        Stephenie Meyer
1591         J.R.R. Tolkien
1363          J.D. Salinger
291               Dan Brown
3              J.K. Rowling
4113           J.K. Rowling
1              J.K. Rowling
22           J.R.R. Tolkien
1990          George Orwell
0              J.K. Rowling
1992        William Golding
4668    William Shakespeare
6772           Rick Riordan
279          John Steinbeck
292               Dan Brown
269            Paulo Coelho
996              Lois Lowry
4916           Markus Zusak
550       Louisa May Alcott
2602       Charlotte Brontë
Name: author, dtype: object

#### What is the fiction/non-fiction breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?

In [36]:
most_ratings_slice['title']

9653                              Twilight (Twilight  #1)
1591                  The Hobbit  or There and Back Again
1363                               The Catcher in the Rye
291                  Angels & Demons (Robert Langdon  #1)
3       Harry Potter and the Prisoner of Azkaban (Harr...
4113    Harry Potter and the Chamber of Secrets (Harry...
1       Harry Potter and the Order of the Phoenix (Har...
22      The Fellowship of the Ring (The Lord of the Ri...
1990                                          Animal Farm
0       Harry Potter and the Half-Blood Prince (Harry ...
1992                                    Lord of the Flies
4668                                     Romeo and Juliet
6772    The Lightning Thief (Percy Jackson and the Oly...
279                                       Of Mice and Men
292                The Da Vinci Code (Robert Langdon  #2)
269                                         The Alchemist
996                             The Giver (The Giver  #1)
4916                                       The Book Thief
550                                          Little Women
2602                                            Jane Eyre
Name: title, dtype: object

In [ ]:
Genres for top 20 titles:
    Twilight: Romance, fantasy, young adult fiction (source: https://en.wikipedia.org/wiki/Twilight_(novel_series))
    The Hobbit: High fantasy, Juvenile fantasy (source: https://en.wikipedia.org/wiki/The_Hobbit)
    The Catcher in the Rye: Realistic fiction, Coming-of-age fiction (source: Wikipedia)
    Angels & Demons/DaVinci Code: Mystery, Detective fiction, Conspiracy fiction, Thriller (source: Wikipedia)
    Harry Potter books: Fantasy, drama, young adult fiction, mystery, thriller, Bildungsroman (source: Wikipedia)
    Fellowship of the Ring: Fantasy (source: Wikipedia)
    Animal Farm: Political satire (source: Wikipedia)
    Lord of the Flies: Allegorical novel (source: Wikipedia)
    Romeo and Juliet: Shakespearean tragedy (source: Wikipedia)
    The Lightnight Thief: Fantasy, Young adult, Greek mythology (source: Wikipedia)
    Of Mice and Men: social realism (https://www.sparknotes.com/lit/micemen/genre/)
    The Alchemist: Novel, Drama, Quest, Fantasy Fiction, Adventure fiction (https://en.wikipedia.org/wiki/The_Alchemist_(novel))
    The Giver: Young adult fiction, Dystopian novel, Science fiction (source: https://en.wikipedia.org/wiki/The_Giver)
    The Book Thief: Novel-Historical Fiction (https://en.wikipedia.org/wiki/The_Book_Thief)
    Little Women: Coming of age, Bildungsroman (source: https://en.wikipedia.org/wiki/Little_Women)
    Jane Eyre: Novel, Victorian literature (source: https://en.wikipedia.org/wiki/Jane_Eyre)

In [37]:
least_ratings_slice['title']

6477                                  Leadership Challenge
9488                                      Worlds of Wonder
6343                              The Road To War  1933 39
6299                 An Odyssey in Learning and Perception
6292             McGraw-Hill's SAT I (McGraw-Hill's SAT I)
9584            Bill Gates: Computer Legend (Famous Lives)
9627     Billy Budd  Sailor and Other Uncompleted Writi...
6063                     American Writers  Supplement VIII
6361     I'll Be Home Before Midnight and I Won't Get P...
5903                               The Deep (Dive Trilogy)
9750     After Collapse: The Regeneration of Complex So...
5599                                            Open House
9801     The Fantastic Vampire: Studies in the Children...
5343                                           Math Fables
9817                                      Mission Possible
251      Out to Eat London 2002 (Lonely Planet Out to Eat)
4963     Canopy: A Work for Voice and Light in Harvard ...
5890            Laguna  I Love You: The Best of "Our Town"
10123    A Cargo of Women: Susannah Watson and the Conv...
9462                                         Day and Night
Name: title, dtype: object

In [35]:
Genres for bottom 20 titles:

6477              James M. Kouzes
9488                 Terry Pastor
6343             Andrew      Hunt
6299            Eleanor J. Gibson
6292          Christopher   Black
9584             Sara Barton-Wood
9627              Herman Melville
6063                   Jay Parini
6361              Anthony E. Wolf
5903                Gordon Korman
9750            Glenn M. Schwartz
5599               Elizabeth Berg
9801            James Craig Holte
5343                    Greg Tang
9817         Kenneth H. Blanchard
251                 Lonely Planet
4963                 David   Ward
5890                    John Weld
10123               Babette Smith
9462     Better Homes and Gardens
Name: author, dtype: object

#### What is the series/not-a-series breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?

In [38]:
most_ratings_slice['series']

9653     True
1591    False
1363    False
291      True
3        True
4113     True
1        True
22       True
1990    False
0        True
1992    False
4668    False
6772     True
279     False
292      True
269     False
996      True
4916    False
550     False
2602    False
Name: series, dtype: bool

In [39]:
least_ratings_slice['series']

6477     False
9488     False
6343     False
6299     False
6292     False
9584     False
9627     False
6063     False
6361     False
5903     False
9750     False
5599     False
9801     False
5343     False
9817     False
251      False
4963     False
5890     False
10123    False
9462     False
Name: series, dtype: bool

#### What is the relationship between book length and being at either extreme in the most- or least-rated books?

In [46]:
most_ratings_slice['num_pages'].sort_values()

279     103
1990    122
1992    182
269     197
996     208
1363    277
4113    341
1591    366
4668    368
6772    375
22      398
3       435
550     449
292     489
9653    501
2602    532
4916    552
0       652
291     736
1       870
Name: num_pages, dtype: int64

In [47]:
least_ratings_slice['num_pages'].sort_values()

9462       32
5343       40
9584       48
6477       50
4963       63
6343      128
5903      148
9801      176
5599      241
9817      242
10123     264
5890      285
6361      288
251       295
9750      336
9488      368
6063      400
6299      654
6292      890
9627     1016
Name: num_pages, dtype: int64

In [42]:
most_ratings_slice['audio_hrs']

9653    0.0
1591    0.0
1363    0.0
291     0.0
3       0.0
4113    0.0
1       0.0
22      0.0
1990    0.0
0       0.0
1992    0.0
4668    0.0
6772    0.0
279     0.0
292     0.0
269     0.0
996     0.0
4916    0.0
550     0.0
2602    0.0
Name: audio_hrs, dtype: float64

In [43]:
least_ratings_slice['audio_hrs']

6477     0.0
9488     0.0
6343     0.0
6299     0.0
6292     0.0
9584     0.0
9627     0.0
6063     0.0
6361     0.0
5903     0.0
9750     0.0
5599     0.0
9801     0.0
5343     0.0
9817     0.0
251      0.0
4963     0.0
5890     0.0
10123    0.0
9462     0.0
Name: audio_hrs, dtype: float64

### What is the age range for the books in the top 20 most-rated books vs the bottom 20 least-rated books?

In [48]:
most_ratings_slice['title']

9653                              Twilight (Twilight  #1)
1591                  The Hobbit  or There and Back Again
1363                               The Catcher in the Rye
291                  Angels & Demons (Robert Langdon  #1)
3       Harry Potter and the Prisoner of Azkaban (Harr...
4113    Harry Potter and the Chamber of Secrets (Harry...
1       Harry Potter and the Order of the Phoenix (Har...
22      The Fellowship of the Ring (The Lord of the Ri...
1990                                          Animal Farm
0       Harry Potter and the Half-Blood Prince (Harry ...
1992                                    Lord of the Flies
4668                                     Romeo and Juliet
6772    The Lightning Thief (Percy Jackson and the Oly...
279                                       Of Mice and Men
292                The Da Vinci Code (Robert Langdon  #2)
269                                         The Alchemist
996                             The Giver (The Giver  #1)
4916                                       The Book Thief
550                                          Little Women
2602                                            Jane Eyre
Name: title, dtype: object

In [50]:
least_ratings_slice['title']

6477                                  Leadership Challenge
9488                                      Worlds of Wonder
6343                              The Road To War  1933 39
6299                 An Odyssey in Learning and Perception
6292             McGraw-Hill's SAT I (McGraw-Hill's SAT I)
9584            Bill Gates: Computer Legend (Famous Lives)
9627     Billy Budd  Sailor and Other Uncompleted Writi...
6063                     American Writers  Supplement VIII
6361     I'll Be Home Before Midnight and I Won't Get P...
5903                               The Deep (Dive Trilogy)
9750     After Collapse: The Regeneration of Complex So...
5599                                            Open House
9801     The Fantastic Vampire: Studies in the Children...
5343                                           Math Fables
9817                                      Mission Possible
251      Out to Eat London 2002 (Lonely Planet Out to Eat)
4963     Canopy: A Work for Voice and Light in Harvard ...
5890            Laguna  I Love You: The Best of "Our Town"
10123    A Cargo of Women: Susannah Watson and the Conv...
9462                                         Day and Night
Name: title, dtype: object

### Is there a variance between the top 20 most-rated and the top 20 most-reviewed?

In [51]:
most_ratings_slice['title']

9653                              Twilight (Twilight  #1)
1591                  The Hobbit  or There and Back Again
1363                               The Catcher in the Rye
291                  Angels & Demons (Robert Langdon  #1)
3       Harry Potter and the Prisoner of Azkaban (Harr...
4113    Harry Potter and the Chamber of Secrets (Harry...
1       Harry Potter and the Order of the Phoenix (Har...
22      The Fellowship of the Ring (The Lord of the Ri...
1990                                          Animal Farm
0       Harry Potter and the Half-Blood Prince (Harry ...
1992                                    Lord of the Flies
4668                                     Romeo and Juliet
6772    The Lightning Thief (Percy Jackson and the Oly...
279                                       Of Mice and Men
292                The Da Vinci Code (Robert Langdon  #2)
269                                         The Alchemist
996                             The Giver (The Giver  #1)
4916                                       The Book Thief
550                                          Little Women
2602                                            Jane Eyre
Name: title, dtype: object

In [53]:
most_reviews_slice = goodread_copy_df.sort_values(by='text_reviews_count', ascending=False).head(20)

In [54]:
most_reviews_slice['title']

9653                              Twilight (Twilight  #1)
4916                                       The Book Thief
996                             The Giver (The Giver  #1)
269                                         The Alchemist
9991                                  Water for Elephants
6772    The Lightning Thief (Percy Jackson and the Oly...
5042                                      Eat  Pray  Love
1942                                     The Glass Castle
1363                               The Catcher in the Rye
3       Harry Potter and the Prisoner of Azkaban (Harr...
292                The Da Vinci Code (Robert Langdon  #2)
480     The Curious Incident of the Dog in the Night-Time
4113    Harry Potter and the Chamber of Secrets (Harry...
2781                            Outlander (Outlander  #1)
1673                                             The Road
1591                  The Hobbit  or There and Back Again
1990                                          Animal Farm
2774                                   My Sister's Keeper
1       Harry Potter and the Order of the Phoenix (Har...
2602                                            Jane Eyre
Name: title, dtype: object

In [44]:
goodread_copy_df.sort_values(by='text_reviews_count', ascending=False)

,bookID,title,author,average_rating,isbn,isbn13,language_code,num_pages,audio_hrs,ratings_count,text_reviews_count,publication_date,publisher,series
9653,41865,Twilight (Twilight #1),Stephenie Meyer,3.59,316015849,9780316015844.0,eng,501,0.0,4597666,94265,2006-09-06,Little Brown and Company,True
4916,19063,The Book Thief,Markus Zusak,4.37,375831002,9780375831003.0,eng,552,0.0,1516367,86881,2006-03-14,Alfred A. Knopf,False
996,3636,The Giver (The Giver #1),Lois Lowry,4.13,385732554,9780385732550.0,eng,208,0.0,1585589,56604,2006-01-24,Ember,True
269,865,The Alchemist,Paulo Coelho,3.86,61122416,9780061122415.0,eng,197,0.0,1631221,55843,1993-05-01,HarperCollins,False
9991,43641,Water for Elephants,Sara Gruen,4.09,1565125606,9781565125605.0,eng,335,0.0,1260027,52759,2007-05-01,Algonquin Books,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6178,25060,Brightness Falls,Jay McInerney,3.74,747553718,9780747553717.0,eng,432,0.0,46,0,2001-08-06,Bloomsbury,False
6152,25002,Writing Degree Zero,Roland Barthes,3.88,809013843,9780809013845.0,eng,96,0.0,19,0,1977-05-01,Hill and Wang,False
6117,24894,Once Said Darlene,William Sleator,3.62,525364102,9780525364108.0,eng,55,0.0,8,0,1979-03-22,Dutton Books,False
6063,24749,American Writers Supplement VIII,Jay Parini,0.00,684806371,9780684806372.0,eng,400,0.0,0,0,2001-05-01,Gale Cengage,False
10537,45572,Fantastic Mr. Fox (Cover to Cover),Roald Dahl,4.05,1855495090,9781855495098.0,eng,0,90.0,7,0,1995-09-15,BBC Audiobooks,False

In [45]:
goodread_copy_df.sort_values(by='publication_date', ascending=False)

,bookID,title,author,average_rating,isbn,isbn13,language_code,num_pages,audio_hrs,ratings_count,text_reviews_count,publication_date,publisher,series
470,1571,Clouds,Aristophanes,3.75,199120099,9780199120093.0,eng,254,0.0,13,2,2069-12-15,Oxford University Press USA,False
5188,20323,The Penguin Companion to European Literature,Anthony Thorlby,4.50,140510354,9780140510355.0,eng,907,0.0,1,0,2069-05-30,Penguin Books,False
437,1516,Aeschylus I: Oresteia (Agamemnon The Libation...,Aeschylus,4.02,226307786,9780226307787.0,eng,171,0.0,712,53,2069-05-15,University of Chicago Press,False
451,1536,Sophocles II: Ajax/Women of Trachis/Electra/Ph...,Sophocles,4.14,226307867,9780226307862.0,eng,254,0.0,5032,36,2069-05-15,University of Chicago Press,False
3257,12645,Aspects of the Theory of Syntax,Noam Chomsky,3.96,262530074,9780262530071.0,eng,261,0.0,296,10,2069-03-15,MIT Press (Cambridge MA),False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1586,Lysistrata,Aristophanes,3.85,451616227,9780451616227.0,eng,98,0.0,19,2,1970-02-01,Signet,False
6027,24601,Paris Spleen,Charles Baudelaire,4.30,811200078,9780811200073.0,eng,118,0.0,7792,176,1970-01-17,New Directions,False
123,253,The Air-Conditioned Nightmare,Henry Miller,3.83,811201066,9780811201063.0,eng,292,0.0,2699,142,1970-01-17,New Directions,False
4665,18132,The Voyage of the “Dawn Treader” (The Chronicl...,C.S. Lewis,4.09,20442602,9780020442608.0,eng,216,0.0,2977,250,1970-01-01,Macmillan Publishing Company/Collier Books,True
7598,31373,In Pursuit of the Proper Sinner (Inspector Lyn...,Elizabeth George,4.10,553575104,9780553575101.0,eng,718,0.0,10608,295,NaT,Bantam Books,True

### Other questions to look into:
#### What is the gender breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?
#### What is the skin color breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?
#### What is the fiction/non-fiction breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?
#### What is the series/not-a-series breakdown in the top 20 most-rated books vs the bottom 20 least-rated books?
#### What is the relationship between book length and being at either extreme in the most- or least-rated books?

#### What gender is in the top 20 most-reviewed books vs the bottom 20 least-reviewed books?
#### What is the skin color breakdown in the top 20 most-reviewed books vs the bottom 20 least-reviewed books?
#### What is the fiction/non-fiction breakdown in the top 20 most-reviewed books vs the bottom 20 least-reviewed books?
#### What is the series/not-a-series breakdown in the top 20 most-reviewed books vs the bottom 20 least-reviewed books?
#### What is the relationship between book length and being at either extreme in the most- or least-rated books?